name: 'Frontend: Publish'

on:
  push:
    branches: ['master', 'main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-frontend/setup-install@v2
      - uses: valitydev/action-setup-thrift@v1
      - name: Codegen
        run: npm run codegen
      - uses: valitydev/action-frontend/publish@v1
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
